
version: 2
jobs:
  build:
    docker:
      - image: node:8

    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: reaction-publish-semantic-release
      - deploy:
          context: reaction-publish-semantic-release
          requires:
            - build
          filters:
            branches:
              only: master
